[package]
name = "win32process"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wmi = "0.11.4"
serde = "1.0.152"
crossbeam-channel = "0.5.6"
anyhow = "1.0.69"
